language: bash

services:
  - docker

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - sudo apt-get update
  - sudo apt-get install -y jq yq

install:
  - pip install -r requirements.txt

script:
  - echo "Running Appdome Travis CI Plugin"
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:latest
    # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - docker run -v $(pwd)/config.yml:/appdome/config.yml galcappdome/travis_plugin:latest /bin/bash -c "/appdome/entrypoint.sh"


after_success:
  - echo "Build succeeded!"

after_failure:
  - echo "Build failed!"