language: bash

services:
  - docker

before_install:
  - echo "Creating Docker volume"
  - ls -l
  - docker volume create appdome_shared_volume
  - ls -l
#before_install:
#  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
#  - sudo apt-get update
##  - sudo apt-get install -y jq yq
#
#install:
#  - pip install -r requirements.txt

script:
  - echo "Running Appdome Travis CI Plugin"
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:latest
  - ls -l $(pwd)
#  - mkdir -p output files
  - ls -l $(pwd)
  - ls -l $(pwd)/output
  - chmod +x $(pwd)/*
  - ls -l $(pwd)/files
  # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - docker run -d --name appdome_container -v $(pwd)/config.yml:/app/config.yml -v appdome_shared_volume:/app/shared galcappdome/travis_plugin:latest /bin/bash -c "/app/create_file.sh"
  - ls -l
#  -
#  - chmod +x $(pwd)/*
#  - chmod +x $(pwd)/appdome_shared_volume/output
#  - chmod +x $(pwd)/appdome_shared_volume/output/*
#  - chmod +x $(pwd)/files
#  - chmod +x $(pwd)/files/*
#  - ls -l $(pwd)
#  - ls -l $(pwd)/appdome_from_container
#  - ls -l $(pwd)/appdome_from_container/output
#  - ls -l $(pwd)/appdome_from_container/files
##  - chown -R travis:travis output files
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
  - docker wait appdome_container
  - docker logs appdome_container
  - ls -l
  - mkdir -p $(pwd)/output
  - mkdir -p $(pwd)/files
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared"
  - mkdir -p $(pwd)/output
  - mkdir -p $(pwd)/files
  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/output/* /host/output
  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/files/* /host/files
  - ls -l
  - ls -l $(pwd)/output
  - ls -l $(pwd)/files
  - ls -l $(pwd)
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared; ls -l /app/shared/output; ls -l /app/shared/files"
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared"
  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/output /host/
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared; ls -l /app/shared/output; ls -l /app/shared/files"
  - ls -l
  - ls -l $(pwd)/output
  - ls -l $(pwd)/files
#  - ls -l $(pwd)
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
#  - ls -l ./output


after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output