language: bash

services:
  - docker

before_install:
  - echo "Creating Docker volume"
  - ls -l
  - docker volume create appdome_shared_volume
  - ls -l
#before_install:
#  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
#  - sudo apt-get update
##  - sudo apt-get install -y jq yq
#
#install:
#  - pip install -r requirements.txt

script:
  - echo "Running Appdome Travis CI Plugin"
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:latest
  - ls -l $(pwd)
#  - mkdir -p output files
  - ls -l $(pwd)
  - ls -l $(pwd)/output
  - chmod +x $(pwd)/*
  - ls -l $(pwd)/files
  # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - docker run -d --name appdome_container -v $(pwd)/config.yml:/appdome/config.yml -v appdome_shared_volume:/appdome/output -v appdome_shared_volume:/appdome/files  galcappdome/travis_plugin:latest /bin/bash -c "/appdome/trigger_travis_build.sh"
  - ls -l
  - ls -l $(pwd)/appdome_shared_volume
  - ls -l $(pwd)/appdome_shared_volume/output
  - ls -l $(pwd)/appdome_shared_volume/files
#  - chmod +x $(pwd)/*
#  - chmod +x $(pwd)/appdome_shared_volume/output
#  - chmod +x $(pwd)/appdome_shared_volume/output/*
#  - chmod +x $(pwd)/files
#  - chmod +x $(pwd)/files/*
#  - ls -l $(pwd)
#  - ls -l $(pwd)/appdome_from_container
#  - ls -l $(pwd)/appdome_from_container/output
#  - ls -l $(pwd)/appdome_from_container/files
##  - chown -R travis:travis output files
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
  - docker wait appdome_container
  - docker logs appdome_container
  - docker run --rm -v appdome_shared_volume:/appdome/output -v $(pwd):/host busybox cp -r /appdome/output /output
  - docker run --rm -v appdome_shared_volume:/appdome/files -v $(pwd):/host busybox cp -r /appdome/files /files
  - ls -l
  - ls -l $(pwd)/output
  - ls -l $(pwd)/files
  - ls -l $(pwd)/appdome_shared_volume
  - ls -l $(pwd)/appdome_shared_volume/output
  - ls -l $(pwd)/appdome_shared_volume/files
#  - ls -l $(pwd)
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
#  - ls -l ./output


after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output