language: bash

services:
  - docker

before_install:
  - echo "Creating Docker volume"
  - ls -l
  - docker volume create appdome_shared_volume
  - ls -l

script:
  - echo "Running Appdome Travis CI Plugin"
  - docker pull galcappdome/travis_plugin:latest
  - ls -l $(pwd)
  - ls -l $(pwd)/output
  - chmod +x $(pwd)/*
  - ls -l $(pwd)/files
  - docker run -d --name appdome_container -v $(pwd)/config.yml:/app/config.yml -v shared:/app/shared galcappdome/travis_plugin:latest /bin/bash -c "/app/create_file.sh"
  - docker wait appdome_container
  - docker logs appdome_container
  - docker cp appdome_container:/app/shared $(pwd)/shared

after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/shared

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/shared
