language: bash

services:
  - docker

#before_install:
#  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
#  - sudo apt-get update
##  - sudo apt-get install -y jq yq
#
#install:
#  - pip install -r requirements.txt

script:
  - echo "Running Appdome Travis CI Plugin"
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:latest
  # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - docker run -d --name appdome_container -v $(pwd)/config.yml:/appdome/config.yml -v $(pwd)/output:/appdome/output galcappdome/travis_plugin:latest /bin/bash -c "/appdome/trigger_travis_build.sh"
  - docker logs appdome_container
  - docker wait appdome_container
  - ls -l $(pwd)
  - ls -l $(pwd)/output
#  -


after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output