language: bash
services:
  - docker
#env:
#  global:
#    - AWS_ACCESS_KEY_ID=****
#    - AWS_SECRET_ACCESS_KEY=***
#    - AWS_DEFAULT_REGION=us-west-1

before_install:
  - echo "Creating Docker volume"
  - docker volume create appdome_shared_volume

before_script:
  - echo "Generating env.list with all environment variables"
  - env | grep -v ' ' | grep -v '^_' > env.list> env.list
  - echo "Contents of env.list:"
  - cat env.list

script:
  - echo "Running Appdome Travis CI Plugin"
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:testing_mekaser
  - ls -l $(pwd)
  - chmod +x $(pwd)/*
  # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - | 
    docker run -d --name appdome_container \
    --env-file env.list \
    -v $(pwd)/config.yml:/appdome/config.yml \
    -v $(pwd)/output:/appdome/output \
    -v $(pwd)/files:/appdome/files \
    galcappdome/travis_plugin:testing_mekaser /bin/bash -c "/appdome/trigger_travis_appdome_workflow.sh"
  - container_exit_code=$(docker wait appdome_container)
  - docker logs appdome_container
  - 'if [ "$container_exit_code" -ne 0 ]; then echo "Container exited with code $container_exit_code"; false; fi'
  - ls -l files
  - ls -l output


after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/files

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/files