language: bash

services:
  - docker
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAUMYEOMD5JGE4UVGR
    - AWS_SECRET_ACCESS_KEY=WDkKLWN\/VFkuP8HjFdzSZLEARtVs4aIn\+8mwOdo5
    - AWS_DEFAULT_REGION=us-west-1
before_install:
  - echo "Creating Docker volume"
  - ls -l
  - docker volume create appdome_shared_volume
#  - ls -l
#  - pip install awscli
#before_install:
#  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
#  - sudo apt-get update
##  - sudo apt-get install -y jq yq
#
#install:
#  - pip install -r requirements.txt

script:
  - echo "Running Appdome Travis CI Plugin"
#  - aws s3 cp s3://appdome-automation-vanilla-apps/Thomas/Gal/travis_plugin_image.tar .
  # Load the Docker image
#  - docker load -i travis_plugin_image.tar
    # Pull the pre-built Docker image
  - docker pull galcappdome/travis_plugin:latest
  - ls -l $(pwd)
#  - mkdir -p output files
  - ls -l $(pwd)
#  - ls -l $(pwd)/output
  - chmod +x $(pwd)/*
  - echo "content of myfile.txt fro travis:"
  - cat myfile.txt
#  - ls -l $(pwd)/files
  # Run the Docker container, mount the config.yml, and execute entrypoint.sh
  - docker run -d --name appdome_container -v $(pwd)/config.yml:/app/config.yml -v $(pwd)/output:/app/output -v $(pwd)/files:/app/files -v $(pwd)/myfile.txt:/app/myfile.txt galcappdome/travis_plugin:latest /bin/bash -c "/app/trigger_travis_appdome_workflow.sh"
  - ls -l
  - ls -l shared
  - ls -l files
  - cat shared/test_file.txt
#  - echo "content of test_file.txt from the container before finished:"
#  - cat myfile.txt
#  - chmod +x $(pwd)/*
#  - chmod +x $(pwd)/appdome_shared_volume/output
#  - chmod +x $(pwd)/appdome_shared_volume/output/*
#  - chmod +x $(pwd)/files
#  - chmod +x $(pwd)/files/*
#  - ls -l $(pwd)
#  - ls -l $(pwd)/appdome_from_container
#  - ls -l $(pwd)/appdome_from_container/output
#  - ls -l $(pwd)/appdome_from_container/files
##  - chown -R travis:travis output files
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
  - ls -l
  - docker wait appdome_container
  - docker logs appdome_container
  - ls -l $(pwd)/shared
  - ls -l $(pwd)/shared/output
  - ls -l $(pwd)/shared/files
  - ls -l files
  - ls -l shared
  - cat shared/test_file.txt
#  - echo "content of test_file.txt from the container after finished:"
#  - cat myfile.txt
#  - cat shared/test_file.txt
##  - ls -l appdome_shared_volume
#  - cat shared/test_file.txt
#  - cat shared/test_file.txt
#  - ls -l
#  - mkdir -p $(pwd)/output
#  - mkdir -p $(pwd)/files
#  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared"
#  - mkdir -p $(pwd)/output
#  - mkdir -p $(pwd)/files
#  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/output/* /host/output
#  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/files/* /host/files
#  - ls -l
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
#  - ls -l $(pwd)
#  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared; ls -l /app/shared/output; ls -l /app/shared/files"
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app"
  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared; /app/trigger_travis_appdome.sh"
  - ls -l
  - ls -l $(pwd)/shared
  - ls -l $(pwd)/shared/output
  - ls -l $(pwd)/shared/files
  - ls -l output
#  - docker run --rm -v appdome_shared_volume:/app/shared -v $(pwd):/host busybox cp -r /app/shared/output /host/
#  - docker run --rm -v appdome_shared_volume:/app/shared alpine sh -c "ls -l /app/shared; ls -l /app/shared/output; ls -l /app/shared/files"
#  - ls -l
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
#  - ls -l $(pwd)
#  - ls -l $(pwd)/output
#  - ls -l $(pwd)/files
#  - ls -l ./output


after_success:
  - echo "Build succeeded!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/shared/output

after_failure:
  - echo "Build failed!"
  - ls -l $(pwd)/output
  - ls -l $(pwd)/shared/output