language: bash

services:
  - docker

script:
  - echo "Installing dependencies"
  - sudo apt-get update
  - sudo apt-get install -y curl jq

  - echo "Uploading app to Appdome"
  - |
    publicLink=$(curl -s --request GET \
      --url "https://fusion.appdome.com/api/v1/upload-link" \
      --header "Authorization: $APPDOME_API_TOKEN")
      
    curl -s -X PUT "$(echo "$publicLink" | jq -r .url)" \
      --header 'Content-Type: application/x-compressed-tar' \
      -T "./files/FileFinder(3).ipa"
    
    app=$(curl -s \
      --request POST \
      --url "https://fusion.appdome.com/api/v1/upload-using-link" \
      --header "Authorization: $APPDOME_API_TOKEN" \
      --header 'content-type: multipart/form-data' \
      --form file_name="./files/FileFinder(3).ipa" \
      --form file_app_id="$(echo "$publicLink" | jq -r .file_id)")

  - echo "Building app on Appdome Fusion Platform"
  - |
    task_id=$(
      curl -s --request POST \
        --url "https://fusion.appdome.com/api/v1/tasks" \
        --header "Authorization: $APPDOME_API_TOKEN" \
        --header 'accept: application/json' \
        --header 'content-type: multipart/form-data' \
        --form action=fuse \
        --form fusion_set_id="$FUSION_SET_ID" \
        --form app_id="$(echo "$app" | jq -r .id)" \
    )
    task_id="$(echo "$task_id" | jq -r .task_id)"
    echo "Task ID: $task_id"

  - echo "Waiting for build to complete"
  - |
    status="running"
    while [ "$status" == "running" ]; do
      sleep 30
      status=$(curl -s --request GET \
        --url "https://fusion.appdome.com/api/v1/tasks/$task_id" \
        --header "Authorization: $APPDOME_API_TOKEN" \
        | jq -r .status)
      echo "Current status: $status"
    done

  - echo "Build completed. Fetching results..."
  - |

    curl -s --request GET \
      --url "https://fusion.appdome.com/api/v1/download/$task_id" \
      --header "Authorization: $APPDOME_API_TOKEN" \
      --output "appdome_result.zip"
    
    unzip -l appdome_result.zip


after_success:
  - echo "Build and API interaction succeeded!"
  - ls -l

after_failure:
  - echo "Build failed!"
