# config.yaml
platform: "ANDROID"
appdome_build:
  APPDOME_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWQ2Yzk4MzAtMTY5OC0xMWVmLWI2NDktMzM3Y2U1NzAwNDY3Iiwic2FsdCI6IjRmMjBjMTRjLWU1MWItNDQ3YS1hMjBjLTNmY2FiNGIxODFlYSJ9.AI5soWJrClObNzD1T0yy_hLWVfLGyam08fhQm5QT4qs"
  APP_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/Apps/FileFinder.aab?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240731%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T084143Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=5e248b3cfab8e537d02d29110ff0efe9fd21fb96a3e9745f2f0a08aee766161e"
  SIGN_OPTIONS: "PRIVATE_SIGNING"
  FUSION_SET_ID: "37015ab0-226d-11ef-a76e-97c41ade4d80"
  SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"
#  SECOND_OUTPUT: "MeKaser_travis_2.aab"
  BUILD_TO_TEST: "None"
  TEAM_ID: "None"
  APPDOME_SERVER_BASE_URL: "https://qamaster.dev.appdome.com/"
  KEYSTORE_FILE: "None"
#  KEYSTORE_PASSWORD: "appdome"
#  KEYSTORE_ALIAS: "appdome"
#  KEYSTORE_KEY_PASSWORD: "appdome"
#