# config.yaml
platform: "ANDROID"
appdome_build:
  APPDOME_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWQ2Yzk4MzAtMTY5OC0xMWVmLWI2NDktMzM3Y2U1NzAwNDY3Iiwic2FsdCI6IjRmMjBjMTRjLWU1MWItNDQ3YS1hMjBjLTNmY2FiNGIxODFlYSJ9.AI5soWJrClObNzD1T0yy_hLWVfLGyam08fhQm5QT4qs"
  APP_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/Apps/FileFinder.aab?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240805%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240805T063011Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=ccdf7517ed3ecec7082c6364553a1400d5def453887db2e983cc433d3055be71"
  SIGN_OPTIONS: "AUTO_DEV_SIGNING"
  FUSION_SET_ID: "37015ab0-226d-11ef-a76e-97c41ade4d80"
  SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"
  SECOND_OUTPUT: "MeKaser_beton_travis_AUTO_DEV_SIGNING.aab"
  BUILD_TO_TEST: "None"
  TEAM_ID: "None"
  APPDOME_SERVER_BASE_URL: "https://qamaster.dev.appdome.com/"
  KEYSTORE_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/appdome.keystore?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240805%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240805T063011Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=568d4b0337ca7c1d2bf88769a5302b4691cda4de961bbdcd3b970a27de3ed263"
  OUTPUT_APP_NAME: "mekaser_beton_output_AUTO_DEV_SIGNING.aab"
#  KEYSTORE_PASSWORD: "appdome"
  KEYSTORE_ALIAS: "appdome"
#  KEYSTORE_KEY_PASSWORD: "appdome"
  BUILD_WITH_LOGS: "true"
#