# config.yaml
platform: "ANDROID"
appdome_build:
  APPDOME_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWQ2Yzk4MzAtMTY5OC0xMWVmLWI2NDktMzM3Y2U1NzAwNDY3Iiwic2FsdCI6IjRmMjBjMTRjLWU1MWItNDQ3YS1hMjBjLTNmY2FiNGIxODFlYSJ9.AI5soWJrClObNzD1T0yy_hLWVfLGyam08fhQm5QT4qs"
#  APP_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/Apps/FileFinder.ipa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240806%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240806T073110Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=3dd8e9face16e28cbccc63ada5da8e94bb2938dadb18acb18dddf11a9ff17bf9"
  APP_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/Apps/FileFinder.aab?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240806%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240806T073110Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=878e76c3592572ccc695fcfcefec66fd251cae5b34035037d8d809e6f2974d3f"
  SIGN_OPTIONS: "SIGN_ON_APPDOME"
#  FUSION_SET_ID: "11c97910-5320-11ef-9f3f-cd47153b0ee7"
  FUSION_SET_ID: "37015ab0-226d-11ef-a76e-97c41ade4d80"
  SIGN_FINGERPRINT: "8DF593C1B6EAA6EADADCE36831FE82B08CAC8D74"
  SECOND_OUTPUT: "MeKaser_beton_travis_SIGN_ON_APPDOME.apk"
  GOOGLE_PLAY_SIGNING: "true"
#  BUILD_TO_TEST: "None"
#  TEAM_ID: "None"
  APPDOME_SERVER_BASE_URL: "https://qamaster.dev.appdome.com/"
  KEYSTORE_FILE: "./files/appdome(5).keystore"
  OUTPUT_APP_NAME: "mekaser_beton_output_PRIVATE_SIGNING.aab"
  KEYSTORE_PASSWORD: "appdome"
  KEYSTORE_ALIAS: "appdome"
  KEYSTORE_KEY_PASSWORD: "appdome"
  BUILD_WITH_LOGS: "true"
  MOBILE_PROVISION_PROFILE_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/Automation.mobileprovision?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240806%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240806T073110Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=b0ef1036012c9e87210bd41d7f048346dfb57e7c80a3b8d2de88b01032dab8ac"
  ENTITLEMENTS_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/AutomationEntitlements.plist?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240806%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240806T073110Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=dad23b2f53b3b83f5fa17700a3a86f86c568ec394e56bd6ac6ccfa36f4e98e28"
  CERTIFICATE_FILE: "https://appdome-automation-vanilla-apps.s3.amazonaws.com/Thomas/PipelineFiles/AutomationCert.p12?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUMYEOMD5JGE4UVGR%2F20240806%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240806T073110Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=f8c8febc3314478e3824c17b25113116b85aa331ffdab5d5337af6e960b13893"
  CERTIFICATE_PASSWORD: "nf1101"
